# Generated by Django 3.1.5 on 2021-01-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('userid', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Number_store',
            },
        ),
    ]
